services:
  mongo:
    image: mongo:4.4.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongoVolume:/data/db"
    networks:
      - intelliot
  server:
    image: intelliot-server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
    environment:
      - "MONGO_URL=${MONGO_URL}"
    ports:
      - "${SERVER_PORT}:80"
    networks:
      - intelliot
    depends_on:
      - mongo
  client:
    image: intelliot-client
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - intelliot
    depends_on:
      - server

volumes:
  mongoVolume:

networks:
  intelliot:
