services:
  mongo:
    image: mongo:4.4.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongoVolume:/data/db"
    networks:
      - intelliot
  server:
    image: intelliot-server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - "MONGO_URL=mongodb://mongo:27017/masDB"
    ports:
      - "8091:80"
    networks:
      - intelliot
    depends_on:
      - mongo
  client:
    image: intelliot-client
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - "SERVER_PORT=8091"
    ports:
      - "8090:80"
    networks:
      - intelliot

volumes:
  mongoVolume:

networks:
  intelliot:
